name: Build, Test and Publish 

run-name: ${{ github.actor }} is running the build, test and publish workflow

on:
#  workflow_dispatch:
#    inputs:
#      branch:
#        description: Inserire il nome della branch
#        required: true
#      slot:
#        description: Inserire il numero di slot
#        required: true

  push:
    branches:
      - main
      - test-workflow

#  pull_request:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Verify npm installation 
        run: pnpm --version

      - name: Run build 
        run: pnpm exec nx run-many --target=build 
      

  test:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm 
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Verify npm installation
        run: pnpm --version

      - name: Run tests
        run: pnpm exec nx run-many --target=test

  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Verify npm installation
        run: pnpm --version

      - name: Authenticate to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > -/.npmrc

      - name: Run publish
        run: pnpm exec nx affected --target=nx-release-publish --access=public
        
